# 训练配置
training:
  batch_size: 8
  learning_rate: 0.005
  num_epochs: 100
  warmup_epochs: 3
  use_amp: true  # 自动混合精度

# 数据配置
data:
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  class_weights: [1.0, 2.5]  # 处理样本不均衡

# 模型配置
model:
  backbone: resnet50_vd
  num_classes: 2
  pretrained: true